In [1]:
import numpy as np
import pandas as pd

# Numpy

### Ejercicio arrays

1. Crear un array `array_1` de dimensión 6 filas y 4 columnas
2. Crear un array `array_2` cambiando las dimensiones a 3 filas y 8 columnas
3. Crear un array `array_3` cambiando las dimensiones a 5 filas y 7 columnas
4. Crear un array `array_4` de zeros y otro de unos de dimension 2 filas, 3 columnas

In [2]:
# Paso 1: Crear un Array `array_1` de Dimensión 6 Filas y 4 Columnas
#array_1 = np.random.randint(0, 100, (6, 4))
array_1 = np.random.randint(0, 100, (6, 4))
print(array_1)
print ("\n")
# Paso 2: Crear un Array `array_2` Cambiando las Dimensiones a 3 Filas y 8 Columnas
array_2 = array_1.reshape (3, 8)
print(array_2)
print ("\n")
# Paso 3: Crear un Array `array_3` Cambiando las Dimensiones a 5 Filas y 7 Columnas
array_3 = np.resize(array_2,(5,7))
print (array_3)
print ("\n")
# Paso 4: Crear un Array `array_4` de Zeros y Otro de Unos de Dimensión 2 Filas y 3 Columnas
array_4 = zeros = np.zeros((2, 3))
print(zeros)
print ("\n")
unos = np.ones((2, 3))
print(unos)

[[38 60 94 95]
 [26 49 37 71]
 [64 94 54 99]
 [35 97 33 82]
 [80 80 85  2]
 [19 23 42 66]]


[[38 60 94 95 26 49 37 71]
 [64 94 54 99 35 97 33 82]
 [80 80 85  2 19 23 42 66]]


[[38 60 94 95 26 49 37]
 [71 64 94 54 99 35 97]
 [33 82 80 80 85  2 19]
 [23 42 66 38 60 94 95]
 [26 49 37 71 64 94 54]]


[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]

## Ejercicio numpy

Imagina que tienes datos de temperatura promedio diaria de una ciudad durante un mes (30 días). Quieres realizar un análisis básico de estos datos usando Numpy para obtener información útil como la temperatura promedio del mes, la temperatura máxima y mínima, y los días en los que la temperatura estuvo por encima de la temperatura promedio.

1. **Crear un array de temperaturas:**

  - Genera un array de Numpy con 30 elementos que representen las temperaturas promedio diarias de la ciudad durante un mes.
  - Que se genere con numeros enteros aleatorios, entre los valores 18 y 29

2. **Calcular estadísticas básicas:**

  - Calcula la temperatura promedio del mes.
  - Encuentra la temperatura máxima y mínima del mes.

3. **Identificar días calurosos:**

  - Identifica los días en los que la temperatura estuvo por encima de la temperatura promedio del mes.

4. **Imprimir resultados:**

  - Imprime la temperatura promedio, máxima y mínima.
  - Imprime los índices (días) en los que la temperatura estuvo por encima del promedio.

In [3]:
# Paso 1: Crear un array de temperaturas para 30 días
#temperaturas = np.array([25, 26, 27, 24, 23, 26, 28, 27, 25, 26, 24, 23, 25, 27, 28, 26, 27, 25, 24, 23, 26, 28, 27, 25, 26, 24, 23, 25, 27, 28])
temperaturas = np.array([25, 26, 27, 24, 23, 26, 28, 27, 25, 26, 24, 23, 25, 27, 28, 26, 27, 25, 24, 23, 26, 28, 27, 25, 26, 24, 23, 25, 27, 28])

temperaturas = np.random.randint(18,30,size=30, dtype=int)
print (temperaturas)

# Paso 2: Calcular estadísticas básicas
Temperatura_media = np.mean(temperaturas)
Temperatura_min = np.min(temperaturas)
Temperatura_max = np.max(temperaturas)


# Paso 3: Identificar días calurosos (con for o utilizar con función numpy wher
for días_calurosos in temperaturas:
    if días_calurosos >= 26:
        print(días_calurosos)
# np.where para encontrar los índices de los días en que la temperatura estuvo por encima del promedio
dias_calurosos = np.where  (temperaturas > Temperatura_media)[0]
print (dias_calurosos)
indices_calor = np.where(temperaturas >= 26)
print(indices_calor[0]+1)


# Paso 4: Imprimir resultados
print(f"Temperatura media: {Temperatura_media:.2f}")
print(f"Temperatura mínima: {Temperatura_min}")
print(f"Temperatura máxima: {Temperatura_max}")
print(f"Días calurosos por encima del promedio:{dias_calurosos + 1}")

[23 24 19 29 24 18 25 26 27 22 27 28 27 19 27 19 18 25 19 22 24 24 25 19
 25 18 26 29 24 29]
29
26
27
27
28
27
27
26
29
29
[ 1  3  4  6  7  8 10 11 12 14 17 20 21 22 24 26 27 28 29]
[ 4  8  9 11 12 13 15 27 28 30]
Temperatura media: 23.70
Temperatura mínima: 18
Temperatura máxima: 29
Días calurosos por encima del promedio:[ 2  4  5  7  8  9 11 12 13 15 18 21 22 23 25 27 28 29 30]

# Pandas

### Ejercicio pandas

1. Sobre nuestro dataframe "df" crea nuevas columnas:
  - **"age_menos_20":** resultado de restarle 20 años al campo 'edad'
  - **"age_mas_10":** resultado de sumarle 10 años al campo 'edad'
  - **"annual_salary_entre_1000":** resultado de dividir el salario anual entre 1000
  - **"salario_mensual":** resultado de dividir el salario anual entre 12
  - **"edad_respecto_media":** a partir del campo 'Gender', generar otro campo tal que si la edad es mayor que la media se informe con 'Mayor que la media' y si es menor se informe con 'Menor que la media'
  
2. Guarda en una variable de tipo lista los nombres de las columnas y muestra el valor de la variable

3.  Muestra las 20 ultimas filas

4. Elimina las columnas 'age_menos_20' y 'annual_salary_entre_1000' del dataframe 'df'

5. Muestra las 8 primeras filas

6. Crea un nuevo dataframe llamado 'df_2' que no tenga el campo 'age_mas_10' (pero mantenga los campos que teníamos en 'df' hasta el punto 8)

7. Muestra la forma de este nuevo df_2, un resumen de su información y la información estadística de este campo

8. Genera la matriz de correlación y obtén alguna conclusión entre las siguientes variables:
  - Age, AnnualSalary, Purchased

In [21]:
df = pd.read_csv('/content/car_data.csv')

In [22]:
# Crea una nueva columna como resultado de restarle 20 años al campo 'edad'
df['age_menos_20'] = df['Age'] -20

# Crea una nueva columna como resultado de sumarle 10 años al campo 'edad'
df['age_mas_10'] = df['Age'] +10

# Crea una nueva columna como resultado de dividir el salario anual entre 1000
df['AnnualSalary_entre_mil'] = df['AnnualSalary']/1000

# Crea una nueva columna como resultado de dividir el salario anual entre 12
df['AnnualSalary_mensual'] = df['AnnualSalary']/12

# Crear la nueva columna usando np.where
df['edad_respecto_media'] = np.where(df['Age'] > df['Age'].mean(),'Mayor que la media', 'Menor que la media')

In [23]:
# 2. Guarda en una variable de tipo lista los nombres de las columnas y muestra el valor de la variable
df.columns
list(df)

['User ID',
 'Gender',
 'Age',
 'AnnualSalary',
 'Purchased',
 'age_menos_20',
 'age_mas_10',
 'AnnualSalary_entre_mil',
 'AnnualSalary_mensual',
 'edad_respecto_media']

In [24]:
# 3.  Muestra las 20 ultimas filas
df.tail(20)

,User ID,Gender,Age,AnnualSalary,Purchased,age_menos_20,age_mas_10,AnnualSalary_entre_mil,AnnualSalary_mensual,edad_respecto_media
980,82,Female,46,23500,1,26,56,23.5,1958.333333,Mayor que la media
981,695,Female,39,79000,0,19,49,79.0,6583.333333,Menor que la media
982,946,Male,39,60500,0,19,49,60.5,5041.666667,Menor que la media
983,676,Male,42,54000,0,22,52,54.0,4500.000000,Mayor que la media
984,649,Female,28,87000,0,8,38,87.0,7250.000000,Menor que la media
985,477,Female,45,77500,0,25,55,77.5,6458.333333,Mayor que la media
986,572,Male,48,33000,1,28,58,33.0,2750.000000,Mayor que la media
987,832,Female,31,71000,0,11,41,71.0,5916.666667,Menor que la media
988,302,Male,33,121500,1,13,43,121.5,10125.000000,Menor que la media
989,420,Female,27,84000,0,7,37,84.0,7000.000000,Menor que la media
990,971,Male,25,56500,0,5,35,56.5,4708.333333,Menor que la media
991,382,Female,30,48500,0,10,40,48.5,4041.666667,Menor que la media
992,168,Female,24,67500,0,4,34,67.5,5625.000000,Menor que la media
993,476,Female,54,136500,0,34,64,136.5,11375.000000,Mayor que la media
994,951,Female,53,104000,1,33,63,104.0,8666.666667,Mayor que la media
995,863,Male,38,59000,0,18,48,59.0,4916.666667,Menor que la media
996,800,Female,47,23500,0,27,57,23.5,1958.333333,Mayor que la media
997,407,Female,28,138500,1,8,38,138.5,11541.666667,Menor que la media
998,299,Female,48,134000,1,28,58,134.0,11166.666667,Mayor que la media
999,687,Female,44,73500,0,24,54,73.5,6125.000000,Mayor que la media

In [25]:
# 4. Elimina las columnas 'age_menos_20' y 'annual_salary_entre_1000' del dataframe 'df'
df.drop(['age_menos_20','AnnualSalary_entre_mil'], axis=1, inplace = True)
print(df.columns)

Index(['User ID', 'Gender', 'Age', 'AnnualSalary', 'Purchased', 'age_mas_10',
       'AnnualSalary_mensual', 'edad_respecto_media'],
      dtype='object')

In [8]:
# 5. Muestra las 8 primeras filas
df.head(8)

   User ID  Gender  Age  AnnualSalary  Purchased
0      385    Male   35         20000          0
1      681    Male   40         43500          0
2      353    Male   49         74000          0
3      895    Male   40        107500          1
4      661    Male   25         79000          0
5      846  Female   47         33500          1
6      219  Female   46        132500          1
7      588    Male   42         64000          0

In [26]:
# 6. Crea un nuevo dataframe llamado 'df_2' que no tenga el campo 'age_mas_10'
# (pero mantenga los campos que teníamos en 'df' hasta el punto 8)
df_2 = df.drop(['age_mas_10'], axis=1)
df_2

,User ID,Gender,Age,AnnualSalary,Purchased,AnnualSalary_mensual,edad_respecto_media
0,385,Male,35,20000,0,1666.666667,Menor que la media
1,681,Male,40,43500,0,3625.000000,Menor que la media
2,353,Male,49,74000,0,6166.666667,Mayor que la media
3,895,Male,40,107500,1,8958.333333,Menor que la media
4,661,Male,25,79000,0,6583.333333,Menor que la media
...,...,...,...,...,...,...,...
995,863,Male,38,59000,0,4916.666667,Menor que la media
996,800,Female,47,23500,0,1958.333333,Mayor que la media
997,407,Female,28,138500,1,11541.666667,Menor que la media
998,299,Female,48,134000,1,11166.666667,Mayor que la media
999,687,Female,44,73500,0,6125.000000,Mayor que la media

In [27]:
# 7. Muestra la forma de este nuevo df_2, un resumen de su información y la información estadística de este campo
df_2.shape
df_2.info()
df_2.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   User ID               1000 non-null   int64
 1   Gender                1000 non-null   object
 2   Age                   1000 non-null   int64
 3   AnnualSalary          1000 non-null   int64
 4   Purchased             1000 non-null   int64
 5   AnnualSalary_mensual  1000 non-null   float64
 6   edad_respecto_media   1000 non-null   object
dtypes: float64(1), int64(4), object(2)
memory usage: 54.8+ KB

,User ID,Age,AnnualSalary,Purchased,AnnualSalary_mensual
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,40.106000,72689.000000,0.402000,6057.416667
std,288.819436,10.707073,34488.341867,0.490547,2874.028489
min,1.000000,18.000000,15000.000000,0.000000,1250.000000
25%,250.750000,32.000000,46375.000000,0.000000,3864.583333
50%,500.500000,40.000000,72000.000000,0.000000,6000.000000
75%,750.250000,48.000000,90000.000000,1.000000,7500.000000
max,1000.000000,63.000000,152500.000000,1.000000,12708.333333

In [28]:
# 8. Genera la matriz de correlación y obtén alguna conclusión entre las siguientes variables
df_columnas = df[['Age', 'AnnualSalary', 'Purchased']]
print(df_columnas)
matriz_correlacion = df_columnas.corr()
print(matriz_correlacion)

     Age  AnnualSalary  Purchased
0     35         20000          0
1     40         43500          0
2     49         74000          0
3     40        107500          1
4     25         79000          0
..   ...           ...        ...
995   38         59000          0
996   47         23500          0
997   28        138500          1
998   48        134000          1
999   44         73500          0

[1000 rows x 3 columns]
                   Age  AnnualSalary  Purchased
Age           1.000000      0.166042   0.616036
AnnualSalary  0.166042      1.000000   0.364974
Purchased     0.616036      0.364974   1.000000

### Ejercicio rename

1. Cambia el nombre de las siguientes columnas sobre el df 'df_renamed'

- Age -> edad
- AnnualSalary -> salario_anual
- Purchased -> comprado

In [29]:
# Age -> edad
# AnnualSalary -> salario_anual
# Purchased -> comprado
df_renamed = df.rename(columns={'Age':'edad','AnnualSalary':'salario_anual','Purchased':'comprado'})
df_renamed.head ()

,User ID,Gender,edad,salario_anual,comprado,age_mas_10,AnnualSalary_mensual,edad_respecto_media
0,385,Male,35,20000,0,45,1666.666667,Menor que la media
1,681,Male,40,43500,0,50,3625.000000,Menor que la media
2,353,Male,49,74000,0,59,6166.666667,Mayor que la media
3,895,Male,40,107500,1,50,8958.333333,Menor que la media
4,661,Male,25,79000,0,35,6583.333333,Menor que la media

### Ejercicio filter

1. df_filtrado_1: edad mayor que 30 años, salario menor a 100.000 y género ha de ser female

2. df_filtrado_2: salario menor que 100.000, edad mayor o igual a 45 y ordenar por su edad de mayor a menor

3. df_filtrado_3: que hayan realizado alguna compra, que sean 'male', que tengan más de 30 años pero menos de 50 y que su salario sea mayor a 100.000, ordenados por edad (de menor a mayor) y salario (de mayor a menor)

In [30]:
# 1. Edad mayor que 30 años, salario menor a 100.000 y género ha de ser female
df_filtrado_1 = df[ (df["Age"] > 30) & (df["AnnualSalary"] < 100000) & (df["Gender"] == "Female")]

# comprobamos que se haya filtrado correctamente
df_filtrado_1.head()

,User ID,Gender,Age,AnnualSalary,Purchased,age_mas_10,AnnualSalary_mensual,edad_respecto_media
5,846,Female,47,33500,1,57,2791.666667,Mayor que la media
12,790,Female,32,72500,0,42,6041.666667,Menor que la media
20,338,Female,39,51500,0,49,4291.666667,Menor que la media
21,134,Female,49,39000,1,59,3250.000000,Mayor que la media
23,294,Female,41,61500,0,51,5125.000000,Mayor que la media

In [31]:
# 2. Salario menor que 100.000, edad mayor o igual a 45 y ordenar por su edad de mayor a menor
df_filtrado_2 = df[ (df["AnnualSalary"] < 100000) & (df["Age"] >= 45)]
df.sort_values(by="Age", ascending=False, inplace=True)
# comprobamos que se haya filtrado correctamente
df_filtrado_2.head()

,User ID,Gender,Age,AnnualSalary,Purchased,age_mas_10,AnnualSalary_mensual,edad_respecto_media
2,353,Male,49,74000,0,59,6166.666667,Mayor que la media
5,846,Female,47,33500,1,57,2791.666667,Mayor que la media
11,408,Male,47,23000,1,57,1916.666667,Mayor que la media
18,926,Male,46,79000,1,56,6583.333333,Mayor que la media
21,134,Female,49,39000,1,59,3250.000000,Mayor que la media

In [32]:
# 3. Que hayan realizado alguna compra, que sean 'male', que tengan más de 30 años pero menos de 50 y que su salario sea mayor a 100.000
# ordenados por edad y salario
df_filtrado_3 = df[ (df["Purchased"] == 1) & (df["Gender"] == "Male") & (df["Age"] > 30) & (df["Age"] < 50) & (df["AnnualSalary"] > 100000)]
# comprobamos que se haya filtrado correctamente
df_filtrado_3.head()

,User ID,Gender,Age,AnnualSalary,Purchased,age_mas_10,AnnualSalary_mensual,edad_respecto_media
865,545,Male,49,119500,1,59,9958.333333,Mayor que la media
921,802,Male,48,106500,1,58,8875.000000,Mayor que la media
700,129,Male,47,105000,1,57,8750.000000,Mayor que la media
623,109,Male,47,118500,1,57,9875.000000,Mayor que la media
471,843,Male,46,131500,1,56,10958.333333,Mayor que la media

### Ejercicio group by

1. Agrupar por `Product` y `Region`, y obtener la suma de las ventas
2. Filtrar el df para incluir solo aquellos productos donde las ventas son mayores que 1000, agrupar por `Product`, y obtener el promedio de las ventas para cada producto
3. Agrupar por `Region`, y obtener la suma de las ventas y el número total de ventas
4. Filtrar el df para incluir solo aquellas regiones donde la suma de ventas es mayor que 2000, agrupar por `Region`, y obtener la suma y el promedio de las ventas para cada región (usar lambda!!!)

In [33]:
# Crear el df de ejemplo
data = {
    'Product': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': [1000, 1500, 800, 1200, 900, 1100, 750, 1300, 850, 950]
}

df = pd.DataFrame(data)
df.head(5)

  Product Region  Sales
0       A  North   1000
1       B  South   1500
2       A   East    800
3       C   West   1200
4       B  North    900

In [34]:
from ast import Expression
# 1: Agrupar por `Product` y `Region`, y obtener la suma de las ventas.
grouped_product_region = df.groupby(['Product', 'Region']).sum().reset_index()
print(grouped_product_region)
#otra forma
df.groupby(['Product', 'Region']).agg({"Sales" : 'sum'}).reset_index()

# 2: Filtrar el df para incluir solo aquellos productos donde las ventas son mayores que 1000,
# agrupar por `Product`, y obtener el promedio de las ventas para cada producto.
df[ (df['Sales']>1000) ].groupby(["Product"]).agg(
    {
        "Sales": ["mean"]
    }
).reset_index().round(2)
# 3: Agrupar por `Region`, y obtener la suma de las ventas y el número total de ventas.
grouped_region = df.groupby('Region').agg(
    {
        "Sales": ["sum", "count"]
    }
).reset_index()
print(grouped_region)

#otra forma
total_sales_region = df.groupby('Region').agg(Total_Sales=('Sales', 'sum'), Count_Sales=('Sales', 'count')).reset_index()
print (total_sales_region)

# 4: Filtrar el df para incluir solo aquellas regiones donde la suma de ventas es mayor que 2000,
# agrupar por `Region`, y obtener la suma y el promedio de las ventas para cada región.
df_fitrado = df.groupby("Region").filter(lambda x: x['Sales'].sum() > 2000 )
df_agrupado_4 = df.groupby("Region").filter(lambda x: x['Sales'].sum() > 2000 ).groupby("Region").agg(suma_ventas = ("Sales", "sum"),

                                 media_ventas = ("Sales", "mean")

                                 ).reset_index().round(2)

df_agrupado_4

  Product Region  Sales
0       A   East   1550
1       A  North   1000
2       A  South    950
3       B  North    900
4       B  South   1500
5       B   West   1300
6       C  North    850
7       C  South   1100
8       C   West   1200
  Region Sales
           sum count
0   East  1550     2
1  North  2750     3
2  South  3550     3
3   West  2500     2
  Region  Total_Sales  Count_Sales
0   East         1550            2
1  North         2750            3
2  South         3550            3
3   West         2500            2

  Region  suma_ventas  media_ventas
0  North         2750        916.67
1  South         3550       1183.33
2   West         2500       1250.00

### Ejercicio pivot & crosstab (opcional)

Tenemos un df que contiene información sobre las compras realizadas por los usuarios en una tienda en línea. Las columnas son las siguientes:

- **User ID:** Identificador único del usuario
- **Gender:** Género del usuario (Male/Female)
- **Age:** Edad del usuario
- **Product Category:** Categoría del producto comprado (Electronics, Clothing, Home, etc.)
- **Purchase Amount:** Monto de la compra

Tenemos que:

1. Crear una tabla dinámica que muestre el monto *total* de las compras por edad y categoría de producto
  - ¿Qué categorías de productos son las más compradas en cada grupo de edad?

2. Crear una tabla de contingencia que muestre la frecuencia de compras por Gender y Product Category.

In [35]:
import pandas as pd
import numpy as np

# Crear el DataFrame de ejemplo
data = {
    'User ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female'],
    'Age': [23, 25, 31, 23, 40, 27, 30, 27, 40, 24],
    'Product Category': ['Electronics', 'Clothing', 'Clothing', 'Home', 'Electronics', 'Home', 'Clothing', 'Home', 'Electronics', 'Clothing'],
    'Purchase Amount': [150, 200, 100, 50, 300, 75, 60, 45, 400, 80]
}

df = pd.DataFrame(data)
df

   User ID  Gender  Age Product Category  Purchase Amount
0        1    Male   23      Electronics              150
1        2  Female   25         Clothing              200
2        3  Female   31         Clothing              100
3        4    Male   23             Home               50
4        5  Female   40      Electronics              300
5        6    Male   27             Home               75
6        7    Male   30         Clothing               60
7        8  Female   27             Home               45
8        9    Male   40      Electronics              400
9       10  Female   24         Clothing               80

In [ ]:
# Crear la tabla dinámica

In [ ]:
# Encontrar la categoría de productos más comprada en cada grupo de edad

In [ ]:
# Crear la tabla de contingencia

In [ ]:
# Encontrar la categoría de productos más popular entre hombres y mujeres

# Ejercicio Streaming

1. Eliminar las columnas con información de id de sesiones, id de dispositivos, lenguaje, localización, calidad de playback y cantidad de interacciones
2. Genero preferido por los hombres
3. Corroborar si los smartphones son el dispositivo en el cual permanecen más tiempo los usuarios mirando streaming
4. Las edades que suelen pagar más Premium
5. El video que tiene más tiempo de reproducción
6. El género que más le gustó a las mujeres (rating)


Una vez realizados los apartados, redactar conclusiones que podríamos obtener de los datos. Como analistas, es importante que los datos sepamos entenderlos y sacar insights de los mismos. Podemos crear hipótesis si no tenemos evidencia suficiente para reflejar X cosa como hecho verídico.

Recurso: streaming.csv

In [49]:
import pandas as pd

import io
# Subimos el archivo a nuestro proyecto
from google.colab import files
uploaded = files.upload()

Saving streaming.csv to streaming.csv

In [59]:
df = pd.read_csv('/content/streaming.csv')

In [60]:
df.head()

,User_ID,Session_ID,Device_ID,Video_ID,Duration_Watched (minutes),Genre,Country,Age,Gender,Subscription_Status,Ratings,Languages,Device_Type,Location,Playback_Quality,Interaction_Events
0,eb4f9229-74df-45f6-baac-cf19241b8b30,cb2142a7-0750-49ed-b8ac-a975fe1ff69a,232,11,90.044525,Sci-Fi,Sudan,56,Female,Premium,3,Spanish,Smartphone,Reedshire,4K,73
1,661d4b59-4328-410a-901c-1e3b4c40c334,3bc0a662-b353-4015-8b0c-55ceb510d13a,549,85,68.973479,Comedy,Cuba,52,Male,Premium,3,Chinese,Desktop,Stevenhaven,SD,22
2,dd3fe9e9-ea82-4891-ab93-8a47c80e3251,bd545b4a-9f54-4e87-b9f8-15ae20b44f22,844,50,42.511343,Comedy,Japan,14,Female,Premium,3,Spanish,Tablet,Vaughntown,HD,41
3,a1b3365b-1d00-4ddf-bc43-02fc9c10c680,0441086d-c59e-478d-a496-5c5b995ecfdb,201,38,53.316660,Documentary,Lao People's Democratic Republic,36,Male,Premium,2,Spanish,Laptop,East Raymondbury,SD,40
4,338d3f91-5f1c-4590-8803-324901826406,0295f01d-7f15-4799-856c-90c688697ef8,700,31,69.437786,Action,Bangladesh,31,Male,Premium,4,German,Laptop,Michaelchester,HD,41

In [61]:
# Eliminar las columnas con información de id de sesiones, id de dispositivos, lenguaje,
#localización, calidad de playback y cantidad de interacciones
print(df.columns)
df.drop(['Session_ID','Device_ID','Languages','Location', 'Playback_Quality', 'Interaction_Events'], axis = 1)

Index(['User_ID', 'Session_ID', 'Device_ID', 'Video_ID',
       'Duration_Watched (minutes)', 'Genre', 'Country', 'Age', 'Gender',
       'Subscription_Status', 'Ratings', 'Languages', 'Device_Type',
       'Location', 'Playback_Quality', 'Interaction_Events'],
      dtype='object')

,User_ID,Video_ID,Duration_Watched (minutes),Genre,Country,Age,Gender,Subscription_Status,Ratings,Device_Type
0,eb4f9229-74df-45f6-baac-cf19241b8b30,11,90.044525,Sci-Fi,Sudan,56,Female,Premium,3,Smartphone
1,661d4b59-4328-410a-901c-1e3b4c40c334,85,68.973479,Comedy,Cuba,52,Male,Premium,3,Desktop
2,dd3fe9e9-ea82-4891-ab93-8a47c80e3251,50,42.511343,Comedy,Japan,14,Female,Premium,3,Tablet
3,a1b3365b-1d00-4ddf-bc43-02fc9c10c680,38,53.316660,Documentary,Lao People's Democratic Republic,36,Male,Premium,2,Laptop
4,338d3f91-5f1c-4590-8803-324901826406,31,69.437786,Action,Bangladesh,31,Male,Premium,4,Laptop
...,...,...,...,...,...,...,...,...,...,...
6209,452e1861-cf88-4021-aaeb-1a32f12033fe,44,21.113901,Thriller,Haiti,63,Male,Premium,3,Smart TV
6210,50e3b026-fb15-4576-bce8-fc08f509b175,26,62.514391,Action,Malaysia,23,Male,Premium,4,Tablet
6211,3daafeb1-4075-4aca-a7ce-e3506b7011d7,22,105.516389,Drama,Saint Martin,34,Male,Premium,5,Tablet
6212,2dc2f81d-feba-437d-8545-733a7ea2bbd6,7,38.963612,Action,Poland,23,Female,Premium,5,Laptop
6213,16e0315a-4993-4ce0-a098-340ea5997f3f,88,78.483631,Drama,Kenya,12,Male,Premium,4,Laptop

In [74]:
#2.Genero preferido por los hombres
hombres = df[df["Gender"] == "Male"]
genero_preferido_hombres = hombres["Genre"].value_counts().idxmax()
print(f"El genero preferido por los hombres es: {genero_preferido_hombres}")

El genero preferido por los hombres es: Documentary

In [75]:
#3. Corroborar si los smartphones son el dispositivo en el cual permanecen más tiempo los usuarios mirando streaming
tipo_dispositivo = df[df['Device_Type'] == 'Smartphone']['Device_Type'].value_counts().idxmax()
print(f"El dispositivo en el cual permanecen más tiempo los usuarios mirando streaming es: {tipo_dispositivo}")

El dispositivo en el cual permanecen más tiempo los usuarios mirando streaming es: Smartphone

In [76]:
#4. Las edades que suelen pagar más Premium
tipo_edad = df[df['Subscription_Status'] == 'Premium']['Age'].value_counts().idxmax()
print(f"Las edades que suelen pagar más Premium son: {tipo_edad}")

Las edades que suelen pagar más Premium son: 40

In [78]:
premium_users = df[df["Subscription_Status"] == "Premium"]
edades_premium = premium_users["Age"].value_counts().sort_values(ascending=False)
edades_premium.head(1)

Age
40    72
Name: count, dtype: int64

In [79]:
#5.El video que tiene más tiempo de reproducción
video_mas_reproducido = df.groupby('Video_ID')['Duration_Watched (minutes)'].sum().idxmax()
print(f"El video que tiene más tiempo de reproducción es: {video_mas_reproducido}")

El video que tiene más tiempo de reproducción es: 11

In [80]:
#6. El género que más le gustó a las mujeres (rating)
genero_preferido_mujeres = df[df['Gender'] == 'Female']['Genre'].value_counts().idxmax()
print(f"El género que más le gustó a las mujeres es: {genero_preferido_mujeres}")

El género que más le gustó a las mujeres es: Thriller

In [93]:
#Conclusiones
print(f"Conclusiones:")

print(f"El genero preferido por los hombres es: {genero_preferido_hombres}")
print(f"El dispositivo en el cual permanecen más tiempo los usuarios mirando streaming es: {tipo_dispositivo}")
print(f"Las edades que suelen pagar más Premium son: {tipo_edad}")
print(f"El video que tiene más tiempo de reproducción es: {video_mas_reproducido}")
print(f"El género que más le gustó a las mujeres es: {genero_preferido_mujeres}")

Conclusiones:
El genero preferido por los hombres es: Documentary
El dispositivo en el cual permanecen más tiempo los usuarios mirando streaming es: Smartphone
Las edades que suelen pagar más Premium son: 40
El video que tiene más tiempo de reproducción es: 11
El género que más le gustó a las mujeres es: Thriller

In [86]:
# Conclusiones a partir de la opción describe
df.describe()

,Device_ID,Video_ID,Duration_Watched (minutes),Age,Ratings,Interaction_Events
count,6214.000000,6214.000000,6214.000000,6214.000000,6214.000000,6214.000000
mean,496.762150,50.323785,60.378389,39.665594,2.987448,50.776794
std,287.681163,28.671178,34.597273,17.571317,1.403304,29.009363
min,1.000000,1.000000,0.055809,10.000000,1.000000,0.000000
25%,248.000000,26.000000,30.413538,24.000000,2.000000,26.000000
50%,493.500000,50.000000,60.765637,40.000000,3.000000,51.000000
75%,742.000000,75.000000,90.874141,55.000000,4.000000,76.000000
max,1000.000000,100.000000,119.999972,70.000000,5.000000,100.000000

Podemos sacar las siguientes conclusiones:
*   La edad media está en 40 años y la máxima en 70 años. Siendo la menor edad 10 años podemos confirmar que los niños no visualizan videos multimedia
*   Teniendo en cuenta el valor edad también observamos que las personas mayores son las que más tiempo dedican a ver vídeos.

In [87]:
# Si consideramos el género que visualiza vídeos hay más mujeres que hombres pero es muy poco significativo
df['Gender'].value_counts()

Gender
Female    3148
Male      3066
Name: count, dtype: int64

In [88]:
# Si sacamos la media de tiempo que dedican, en función del género, a ver vídeos podemos confirmar que no es un dato relevante
df.groupby('Gender')['Duration_Watched (minutes)'].mean()

Gender
Female    60.562161
Male      60.189701
Name: Duration_Watched (minutes), dtype: float64

In [89]:
# El tipo de dispositivo más usado para ver vídeos es Smart TV
df['Device_Type'].value_counts()

Device_Type
Smart TV      1306
Desktop       1270
Smartphone    1233
Tablet        1217
Laptop        1188
Name: count, dtype: int64